
import pg from 'pg';
import dotenv from 'dotenv';
import { v4 as uuidv4 } from 'uuid';
import path from 'path';
import { fileURLToPath } from 'url';

// Load .env from server root (one level down from here? No, correct is current dir if running from server/)
// Script will be in server/seed_bubbles.js.
// .env is likely in server/.env or project root?
// Assuming server/.env based on index.js logic. (dotenv.config() in index.js).

dotenv.config();

const { Pool } = pg;

async function seed() {
    console.log("🌱 Seeding Done Bubbles...");

    const pool = new Pool({
        user: process.env.DB_USER || 'postgres',
        host: process.env.DB_HOST || 'localhost',
        database: process.env.DB_NAME || 'alimanager',
        password: process.env.DB_PASSWORD || '',
        port: process.env.DB_PORT ? parseInt(process.env.DB_PORT) : 5433,
    });

    try {
        // 1. Find Alisara
        console.log("   Connecting to DB...");
        const cRes = await pool.query("SELECT * FROM users WHERE LOWER(display_name) LIKE '%alisara%' LIMIT 1");
        if (cRes.rows.length === 0) {
            console.error("❌ Alisara not found!");
            await pool.end();
            process.exit(1);
        }
        const alisara = cRes.rows[0];
        const uid = alisara.user_id_fk || alisara.id;
        console.log(`✅ Found Alisara (UID: ${uid})`);

        // 2. Insert Tasks
        console.log("   Creating 6 Done Tasks...");
        for (let i = 1; i <= 6; i++) {
            const id = uuidv4();
            await pool.query(`
                INSERT INTO tasks (
                    id, title, description, status, priority, 
                    organization_id, created_by,
                    created_at, updated_at, completed_at, due_date
                ) VALUES (
                    $1, $2, $3, 'done', '4', 
                    $4, $5,
                    NOW(), NOW(), NOW(), NOW()
                )
            `, [
                id,
                `Bubble Stack Seed ${i}`,
                'Auto-generated by seed script',
                alisara.organization_id,
                uid
            ]);

            // Assign to Alisara
            await pool.query(`INSERT INTO task_assignments (task_id, user_id) VALUES ($1, $2)`, [id, uid]);
        }
        console.log("✨ Done! 6 tasks created. Refresh the app.");
        await pool.end();
        process.exit(0);

    } catch (e) {
        console.error("❌ Seed Failed:", e);
        await pool.end();
        process.exit(1);
    }
}

seed();
